version: "3.8"

services:
  my_service:
    container_name: "my_nginx_container"
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - mynetwork
  redis:
    image: redis:latest
    networks:
      - mynetwork
  database:
    container_name: "my_sql_data"
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: qwerty1234
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork


volumes:
  mysql_data:


networks:
  mynetwork: